surname = input("surname: ")
first_name = input("first name: ")
street = input("street: ")
number = input("number: ")
place = input("place: ")
zipcode = input("zipcode: ")

print(first_name, surname)
print(street, number)
print(zipcode, place)
